name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
    types: [opened, synchronize, closed]
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
            go-version: 1.17.x
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
